# permissions for end users to view stocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stock-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
  name: stock-viewer-role
rules:
- apiGroups:
  - opendata.example.com
  resources:
  - stocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opendata.example.com
  resources:
  - stocks/status
  verbs:
  - get
