kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lo-dev-v1.26.2
nodes:
- role: control-plane
  image: kindest/node:v1.26.2
- role: worker
  image: kindest/node:v1.26.2
- role: worker
  image: kindest/node:v1.26.2
