apiVersion: v1
kind: Namespace
metadata:
  name: echo
---
kind: Pod
apiVersion: v1
metadata:
  name: http-echo-pod
  namespace: echo
  labels:
    app: http-echo-pod
spec:
  containers:
    - name: foo-app
      image: ealen/echo-server:0.7.0
      env:
        - name: PORT
          value: "5678"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: echo
spec:
  selector:
    matchLabels:
      app: http-echo
  replicas: 2
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: http-echo
          image: ealen/echo-server:0.7.0
          env:
            - name: PORT
              value: "5678"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: echo
spec:
  type: NodePort
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 5678
      nodePort: 32567
      targetPort: 5678